name: ld-chem
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - netcdf4
  - numba
  - numpy
  - pandas
  - pyyaml
  - scipy
  - xarray
  - matplotlib
  - pytest
  - pytest-cov
  - pip:
      - -e .[test]
