[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ld-chem"
version = "0.1.0"
description = "Lagrangian Droplets with Chemistry Model"
readme = "README.md"
requires-python = ">=3.10"
license = "BSD-2-Clause"
authors = [
    {name = "Laura Fierce", email = "laura.fierce@pnnl.gov"},
    {name = "Payton Beeler", email = "payton.beeler@pnnl.gov"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "xarray",
    "netCDF4",
    "numba",
    "pyyaml",
    "mat73",
    "setuptools",
    "part2pop @ git+https://github.com/pnnl/part2pop.git@main"
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov",
    "black",
    "flake8",
]
test = [
    "pytest>=6.0",
    "pytest-cov>=4",
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
]

[project.urls]
Homepage = "https://github.com/pnnl/LD-Chem"
Documentation = "https://github.com/pnnl/LD-Chem"
Repository = "https://github.com/pnnl/LD-Chem.git"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ld_chem = [
    "species_data/*.dat",
    "mechanisms/*.dat",
]
